### ISSUE TITLE
GitHub CSS for `[` and `]` around footnote calls interfering with user content

### ISSUE THREAD

**Issue by wooorm** [github/cmark-gfm#238]
(Note: this is more an issue with GH CSS rather than `cmark-gfm` or GFM)

Users are able to write HTML in markdown on GitHub. For example:

```markdown
Hi, <sup><a href="#">world</a></sup>
```

The new footnotes use similar markup and use CSS to add brackets around footnote:

```css
.markdown-body sup > a::before {
  content: "[";
}
.markdown-body sup > a::after {
  content: "]";
}
```

This results in the previous markdown being rendered as:

Hi, <sup><a href="#">world</a></sup>

Would it perhaps make sense to use:

```css
[data-footnote-ref]::before {
  content: "[";
}
[data-footnote-ref]::after {
  content: "]";
}
```
